### ISSUE TITLE
[V6] _keep_alive thread fails when bridge disconnects for too long

### ISSUE THREAD

**Issue by sidoh** [happyleavesaoc/python-limitlessled#16]
My guess is that the thread crashes here:

https://github.com/happyleavesaoc/python-limitlessled/blob/master/limitlessled/bridge.py#L230

Because 

```python
self._send_raw(command)
```

Is throwing a socket exception with something like "no route to host".

The effect is that a hub going offline for more than 20 seconds or so causes the client to stop working until `_reconnect` is force-called.

**Comment by corneyl** [comment]
I also experienced situations in which the connection to the bridge was lost, while the bridge itself was still reachable. At least the web interface was reachable and I could use the MiLight app.
In my case it's the Raspberry Pi (with Home Assistant) which has an unstable connection. A restart of HA solves the situation, but this makes it impossible to use limitlessleds/milight in a reliable way.

Maybe it's possible to restart the consumer/keep-alive thread based on `thread.isAlive()` so threads are assured to run no matter what exceptions are thrown?
Thanks!

**Comment by corneyl** [comment]
I've found another bug causing disconnects. Now testing the [following code](/corneyl/python-limitlessled/tree/fix-reconnect-bug) for a while to see how stable it is on a wobbly connection, first results look good.

**Comment by corneyl** [comment]
This one can be closed since #18 is merged
