### ISSUE TITLE
Version 5 bridge broken

### ISSUE THREAD

**Issue by jasonmhite** [happyleavesaoc/python-limitlessled#17]
It looks like #7 broke support for my version 5 bridge. I noticed this after upgrading Home Assistant the other day, suddenly my Limitlessled hub stopped responding. Working through it, it looks like there isn't any response from the bridge. E.g.

```
from limitlessled.bridge import Bridge
from limitlessled.group.rgbw import RGBW

b = Bridge("...", port=8899, version=5)
l = b.add_group(4, "lamp", RGBW)

l.on = True
```

does nothing, whereas if I downgrade to the commit tagged as 1.0.2 it works fine. Am I just doing something wrong? I'm willing to do the legwork to debug this and fix it, but I need a little guidance.

**Comment by corneyl** [comment]
@jasonmhite This should be fixed in v1.0.8, can you check this?

**Comment by happyleavesaoc** [comment]
@jasonmhite any update?

**Comment by ypollart** [comment]
Hi there, I'm also here because I can't get Home Assistant to control my lights, although it worked in the past. 

I've got a v5 bridge and got exactly the same problem, even with 1.0.8. 

My lights do not seem to receive any command using the lib, whereas the milight android app works like a charm.

Using the example code under python CLI does nothing.

**Comment by jasonmhite** [comment]
@happyleavesaoc Ah, sorry been busy at work. I'm not using LimitlessLED anymore, but I pulled them out and it seemed to work with the newer version for my basic tests. Just tried turning a bulb on and off.

**Comment by ypollart** [comment]
I've tested the v1.0.8 again and it's working fine. I've been struggling with my setup for a few days and I figured out that my network configuration was to blame. My RPI and the Wifi bridge are not on the same subnet and my RPI did not have a route for reaching the bridge, so the UDP packets were sent to oblivion.
