### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by kamaradclimber** [happyleavesaoc/python-limitlessled#3]
Could you release a new version of this package on pypi (so I can use easily my patch) ?

Thanks

**Comment by happyleavesaoc** [comment]
I'll try to do this tonight or over the weekend at the latest.

**Comment by kamaradclimber** [comment]
thanks a lot

**Comment by happyleavesaoc** [comment]
1.0.1 available. Sorry for the delay.

**Comment by kamaradclimber** [comment]
thx!
