### ISSUE TITLE
V6 maintainer wanted

### ISSUE THREAD

**Issue by happyleavesaoc** [happyleavesaoc/python-limitlessled#31]
Looking for someone with a V6 bridge who is willing to test and approve V6-bridge related pull requests. I only have a V5 bridge.

**Comment by durzo** [comment]
I have a v6 bridge and I would be willing to perform tests.

Alternatively, I can donate you a brand new v6 bridge

**Comment by jtitley** [comment]
I can help too although I'm not a python expert. On a similar note I've been having trouble with Home Assistant where after a while commands don't work. Inspecting the code I notice in keep alive thread there is no error handling on socket send. The result is just ignored. I'm not a python programmer so forgive me if I'm wrong here. If the socket is blocking and the connection drops, will not the subsequent read either block or raise an unhandled socket exception which would terminate the thread?

**Comment by smwa** [comment]
I'm available for V6 development and testing. I've been using this project via home-assistant for years and would love to make sure it doesn't go defunct yet. Let me know how I can help!

**Comment by happyleavesaoc** [comment]
@smwa that would be great. sent you an invite.
